version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
      # - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
      # - 5051:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  redis-insight:
  postgres-data:
  redis-data:
  pgadmin-data:
